from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


class BestProject(BaseModel):
    """Best project identified from the developer's public repositories."""
    name: Optional[str] = Field(None, description="Repository name, or null if insufficient evidence")
    reason: str = Field(..., description="Justification grounded in the evidence")


class DeveloperAnalysis(BaseModel):
    """Strict structured analysis output generated by the AI reviewer."""
    overall_score: int = Field(..., ge=0, le=100, description="Holistic assessment from 0 to 100 based on public evidence")
    technical_depth_score: int = Field(..., ge=0, le=100, description="Technical diversity and project complexity signals")
    project_quality_score: int = Field(..., ge=0, le=100, description="Original projects, stars, descriptions, and completeness")
    documentation_score: int = Field(..., ge=0, le=100, description="README presence, descriptions, topics, and license")
    consistency_score: int = Field(..., ge=0, le=100, description="Recent activity, active projects, and maintenance pattern")

    developer_personality: str = Field(..., description="Developer archetype based on observable GitHub behavior (approx 2-5 words)")
    strongest_signal: str = Field(..., description="Concise statement describing the strongest positive signal")
    biggest_weakness: str = Field(..., description="Concise, constructive statement describing the biggest area for improvement")
    best_project: BestProject = Field(..., description="The standout repository based on evidence")
    roast: str = Field(..., description="A technically grounded, playful roast (2-5 sentences)")
    recommendations: List[str] = Field(..., description="Exactly 3 actionable, specific recommendations")

    @field_validator("recommendations")
    @classmethod
    def validate_recommendations(cls, v: List[str]) -> List[str]:
        if len(v) != 3:
            raise ValueError(f"recommendations must contain exactly 3 items, got {len(v)}")
        for item in v:
            if not isinstance(item, str) or not item.strip():
                raise ValueError("Each recommendation must be a non-empty string")
        return v


class AnalyzeGithubResponse(BaseModel):
    """API response model for AI GitHub analysis."""
    username: str
    analysis: DeveloperAnalysis
