from typing import Optional, List, Dict
from pydantic import BaseModel, Field, field_validator


class BestProject(BaseModel):
    """Standout project identified from the developer's public repositories."""
    name: Optional[str] = Field(None, description="Repository name, or null if insufficient evidence")
    reason: str = Field(..., description="Justification grounded strictly in the evidence")


class DeveloperDNA(BaseModel):
    """Measurable engineering archetype dimensions (each 0–100)."""
    builder: int = Field(default=50, ge=0, le=100, description="Drive to build and ship working applications")
    experimenter: int = Field(default=50, ge=0, le=100, description="Willingness to try varied technologies and stacks")
    documenter: int = Field(default=50, ge=0, le=100, description="Commitment to documentation, READMEs, and licenses")
    maintainer: int = Field(default=50, ge=0, le=100, description="Habit of updating and maintaining existing repos")
    open_source: int = Field(default=50, ge=0, le=100, description="Community engagement, stars, forks, and collaboration")
    specialist: int = Field(default=50, ge=0, le=100, description="Deep focus in a primary language or domain")
    explorer: int = Field(default=50, ge=0, le=100, description="Breadth of topics, tools, and novel repositories")


class TechLanguage(BaseModel):
    """Structured technology proficiency signal based on actual repository counts."""
    name: str = Field(..., description="Language name")
    score: int = Field(default=50, ge=0, le=100, description="Relative proficiency/prominence signal 0-100")
    repository_count: int = Field(default=0, ge=0, description="Number of repositories using this language")


class TechStackFingerprint(BaseModel):
    """Tech stack fingerprint containing actual repository language data."""
    languages: List[TechLanguage] = Field(default_factory=list)


class AssessmentItem(BaseModel):
    """Structured strength or weakness item."""
    title: str = Field(..., description="Concise title")
    description: str = Field(..., description="Evidence-grounded explanation")


class ActionPlanItem(BaseModel):
    """Prioritized action item for developer growth."""
    title: str = Field(..., description="Specific, realistic action title")
    reason: str = Field(..., description="Evidence-based justification grounded in detected gaps")
    expected_impact: str = Field(..., description="Measurable impact on GitHub presence")
    priority: str = Field(default="Medium", description="Priority level: High, Medium, or Low")


class RecruiterSummary(BaseModel):
    """Professional, objective assessment for hiring managers and recruiters."""
    candidate_snapshot: str = Field(default="", description="High-level engineering candidate profile")
    technical_strengths: List[str] = Field(default_factory=list, description="Observed engineering strengths")
    strongest_projects: List[str] = Field(default_factory=list, description="Projects with clearest technical merit")
    technology_breadth: str = Field(default="", description="Assessment of language and domain breadth")
    engineering_signals: List[str] = Field(default_factory=list, description="Key code and repository signals")
    documentation_quality: str = Field(default="", description="Objectively observed documentation habits")
    activity_consistency: str = Field(default="", description="Maintenance patterns and recent activity")
    areas_to_improve: List[str] = Field(default_factory=list, description="Constructive areas for technical growth")
    overall_impression: str = Field(default="", description="Objective summary grounded solely in GitHub evidence")


class DeveloperAnalysis(BaseModel):
    """Comprehensive structured analysis output generated by the AI reviewer."""
    overall_score: int = Field(..., ge=0, le=100, description="Holistic assessment from 0 to 100 based on public evidence")
    technical_depth_score: int = Field(..., ge=0, le=100, description="Technical diversity and project complexity signals")
    project_quality_score: int = Field(..., ge=0, le=100, description="Original projects, stars, descriptions, and completeness")
    documentation_score: int = Field(..., ge=0, le=100, description="README presence, descriptions, topics, and license")
    consistency_score: int = Field(..., ge=0, le=100, description="Recent activity, active projects, and maintenance pattern")

    developer_personality: str = Field(..., description="Developer archetype based on observable GitHub behavior")
    strongest_signal: str = Field(..., description="Concise statement describing the strongest positive signal")
    biggest_weakness: str = Field(..., description="Concise, constructive statement describing the biggest area for improvement")
    best_project: BestProject = Field(..., description="Standout repository based on evidence")
    roast: str = Field(..., description="Technically grounded, evidence-based roast")
    recommendations: List[str] = Field(..., description="Exactly 3 actionable, specific recommendations")

    # Feature Pack V3 additions
    one_line_roast: str = Field(default="", description="Shareable single-sentence roast (< 150 chars)")
    roast_level: str = Field(default="brutal", description="Intensity level used: friendly, brutal, nuclear")
    developer_dna: DeveloperDNA = Field(default_factory=DeveloperDNA, description="Measurable behavioral dimensions")
    tech_stack_fingerprint: TechStackFingerprint = Field(default_factory=TechStackFingerprint, description="Language usage fingerprint")
    strengths: List[AssessmentItem] = Field(default_factory=list, description="Exactly 3 evidence-grounded strengths")
    weaknesses: List[AssessmentItem] = Field(default_factory=list, description="Exactly 3 evidence-grounded weaknesses")
    action_plan: List[ActionPlanItem] = Field(default_factory=list, description="3-5 prioritized growth actions")
    league: str = Field(default="Builder", description="Deterministic league tier derived from overall score")
    league_min_score: int = Field(default=40, description="Minimum score boundary for this league")
    league_max_score: int = Field(default=59, description="Maximum score boundary for this league")
    percentile_status: str = Field(default="Benchmark data developing", description="Honest status of global percentile benchmarks")
    recruiter_summary: RecruiterSummary = Field(default_factory=RecruiterSummary, description="Professional recruiter mode summary")

    @field_validator("recommendations")
    @classmethod
    def validate_recommendations(cls, v: List[str]) -> List[str]:
        if len(v) != 3:
            raise ValueError(f"recommendations must contain exactly 3 items, got {len(v)}")
        for item in v:
            if not isinstance(item, str) or not item.strip():
                raise ValueError("Each recommendation must be a non-empty string")
        return v


class AnalyzeGithubRequest(BaseModel):
    """Optional payload for configuring analysis options such as roast level."""
    roast_level: Optional[str] = Field(default="brutal", description="Roast intensity: friendly, brutal, nuclear")


class AnalyzeGithubResponse(BaseModel):
    """API response model for AI GitHub analysis."""
    username: str
    analysis: DeveloperAnalysis
